apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-hive-hs2
  labels:
    app: {{ template "fullname" . }}-hive-hs2
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.hive_hs2.count }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-hive-hs2
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: {{ .Values.global.repo }}/{{ .Values.hive_hs2.image }}
        name: {{ template "fullname" . }}-hive-hs2
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "{{ .Values.hive_hs2.mem }}"
            cpu: "{{ .Values.hive_hs2.cpu }}"
        volumeMounts:
        - mountPath: /opt/barbarian/hadoop/etc/hadoop
          name: yarn-cfg-volume
        - name: hive-cfg-volume
          mountPath: /opt/barbarian/hive/conf
        - name: tez-cfg-volume
          mountPath: /opt/barbarian/tez/conf
        - name: slider-cfg-volume
          mountPath: /opt/barbarian/slider/conf
        ports:
        - containerPort: 10000
          name: server
        - containerPort: 10002
          name: webui-address
        command:
        - sh
        - -c
        - "/opt/barbarian/control/start-hiveserver2"
      volumes:
      - name: yarn-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-hadoop-conf
      - name: hive-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-hive-conf
      - name: tez-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-tez-conf
      - name: slider-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-slider-conf
