apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-hive-hs2-init
  labels:
    app: {{ template "fullname" . }}-hive-hs2-init
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-hive-hs2-init
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: {{ .Values.global.repo }}/{{ .Values.hive_hs2.image }}
        name: {{ template "fullname" . }}-hive-hs2
        securityContext:
          allowPrivilegeEscalation: false
        command:
        - sh
        - -c
        - "/usr/bin/true"
      initContainers:
      - name: mkdir-tmp
        image: {{ .Values.global.repo }}/{{ .Values.hive_hs2.image }}
        command:
        - sh
        - -c 
        - "/opt/barbarian/control/init.sh && bash /opt/barbarian/hadoop/bin/hadoop fs \
          -mkdir -p /tmp \
          && bash /opt/barbarian/hadoop/bin/hadoop fs \
          -mkdir -p /apps/tez \
          && bash /opt/barbarian/hadoop/bin/hadoop fs \
          -mkdir -p /user/hadoop \
          && bash /opt/barbarian/hadoop/bin/hadoop fs \
          -rm -r -f .yarn/package/service \
          && bash /opt/barbarian/hadoop/bin/hadoop fs \
          -mkdir -p .yarn/package/service \
          && bash /opt/barbarian/hadoop/bin/hadoop fs \
          -rm -r -f .yarn/package/LLAP \
          && bash /opt/barbarian/hadoop/bin/hadoop fs \
          -mkdir -p .yarn/package/LLAP \
          && HADOOP_COMMON_HOME=/opt/barbarian/hadoop HADOOP_HDFS_HOME=/opt/barbarian/hadoop \
          HADOOP_YARN_HOME=/opt/barbarian/hadoop \
          bash /opt/barbarian/hadoop/bin/yarn app -enableFastLaunch .yarn/package/service"
        volumeMounts:
        - name: yarn-cfg-volume
          mountPath: "/opt/barbarian/hadoop/etc/hadoop"
      {{- if .Values.global.tez_init }}
      - name: put-tez-tgz
        image: {{ .Values.global.repo }}/{{ .Values.hive_hs2.image }}
        command:
        - sh
        - -c 
        - "/opt/barbarian/control/init.sh && bash /opt/barbarian/hadoop/bin/hadoop fs \
          -put -f /opt/barbarian/tez.tar.gz /apps/tez/tez.tar.gz"
        volumeMounts:
        - name: yarn-cfg-volume
          mountPath: "/opt/barbarian/hadoop/etc/hadoop"
      {{- end }}
      {{- if .Values.hive_hs2.llapd_enabled }}
      - name: start-hive-llap
        image: {{ .Values.global.repo }}/{{ .Values.hive_hs2.image }}
        command:
        - sh
        - -c 
        - "/opt/barbarian/control/init.sh && \
          bash -c 'cd /tmp; /opt/barbarian/hive/bin/hive --service llap --size {{ .Values.hive_hs2.llapd_mem }} -i {{ .Values.hive_hs2.llapd_count }} -n llaps -z -d /tmp \
          -j /opt/barbarian/hadoop/share/hadoop/yarn/hadoop-yarn-api-3.1.2-badh1.jar,/opt/barbarian/hadoop/share/hadoop/yarn/hadoop-yarn-common-3.1.2-badh1.jar,/opt/barbarian/hadoop/share/hadoop/yarn/hadoop-yarn-client-3.1.2-badh1.jar,/opt/barbarian/hadoop/share/hadoop/common/hadoop-common-3.1.2-badh1.jar; \
          /opt/barbarian/hadoop/bin/yarn app -flex llaps -component llap +{{ .Values.hive_hs2.llapd_count }}'"
        volumeMounts:
        - name: hive-cfg-volume
          mountPath: "/opt/barbarian/hive/conf"
        - name: tez-cfg-volume
          mountPath: "/opt/barbarian/tez/conf"
        - name: yarn-cfg-volume
          mountPath: "/opt/barbarian/hadoop/etc/hadoop"
        - name: slider-cfg-volume
          mountPath: "/opt/barbarian/slider/conf"
      {{- end }}
      volumes:
      - name: yarn-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-hadoop-conf
      - name: hive-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-hive-conf
      - name: tez-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-tez-conf
      - name: slider-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-slider-conf
