apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hive_hms.service.name }}
  labels:
    app: {{ template "fullname" . }}-hive-hms
spec:
  ports:
  - port: 9083
    name: server
  selector:
    app: {{ template "fullname" . }}-hive-hms
