kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.hive_hs2.service.name }}
  labels:
    app: {{ template "fullname" . }}-hive-hs2
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: 10000
    name: server
  - port: 10002
    name: webui-address
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}-hive-hs2
