apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ignite.service.name }}
  labels:
    app: {{ template "fullname" . }}-ignite
spec:
  ports:
  - port: 10500
    name: server
  selector:
    app: {{ template "fullname" . }}-ignite
