apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-ignite
  labels:
    app: {{ template "fullname" . }}-ignite
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ .Values.ignite.service.name }}
  replicas: {{ .Values.ignite.count }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-ignite
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - {{ template "fullname" . }}-ignite
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: {{ .Values.global.repo }}/{{ .Values.ignite.image }}
        env:
        - name: GLIBC_REPO
          value: {{ .Values.global.glibc_repo }}
        - name: GLIBC_VERSION
          value: {{ .Values.global.glibc_version }}
        - name: JAVA8_DOWNLOAD
          value: {{ .Values.global.java8_download }}
        - name: JAVA_INSTALL_VERSION
          value: {{ .Values.global.java8_install_version }}
        - name: BASH_REPO
          value: {{ .Values.global.bash_repo }}
        - name: BASH_APK
          value: {{ .Values.global.bash_apk }}
        - name: BASH_READLINE_APK
          value: {{ .Values.global.bash_readline_apk }}
        - name: BASH_NCURSES_APK
          value: {{ .Values.global.bash_ncurses_apk }}
        name: {{ template "fullname" . }}-ignite
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /opt/barbarian/ignite/config
          name: igfs-cfg-volume
        - mountPath: /opt/barbarian/ignite/work
          name: igfs-work-volume
        - mountPath: /opt/barbarian/hadoop/etc/hadoop
          name: hadoop-cfg-volume
        resources:
          limits:
            memory: {{ .Values.ignite.mem }}
          requests:
            memory: {{ .Values.ignite.mem }}
            cpu: {{ .Values.ignite.cpu }}
        ports:
        - containerPort: 10500
          name: server
        command:
        - sh
        - -c
        - "/opt/barbarian/control/init.sh && /opt/barbarian/control/start-ignite"
      volumes:
      - name: igfs-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-ignite-conf
      - name: hadoop-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-hadoop-conf
      - name: igfs-work-volume
        emptyDir: {}
