apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-slider-conf
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  slider-client.xml: |-
{{ tpl (.Files.Get "files/slider/slider-client.xml") . | indent 4 }}
  slider-env.sh: |-
{{ tpl (.Files.Get "files/slider/slider-env.sh") . | indent 4 }}
