apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-tez-conf
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tez-site.xml: |-
{{ tpl (.Files.Get "files/tez/tez-site.xml") . | indent 4 }}
