apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.yarn_nm.service.name }}
  labels:
    app: yarn-nm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: 45454
    name: server
  - port: 8042
    name: webui-address
  - port: 15551
    name: llap-shuffle
  - port: 15002
    name: llap-daemon
  - port: 15003
    name: llap-rpc
  clusterIP: None
  selector:
    app: yarn-nm
