apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-yarn-rm
  labels:
    app: {{ template "fullname" . }}-yarn-rm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ .Values.yarn_rm.service.name }}
  {{- if .Values.yarn_rm.ha_enabled }}
  replicas: 2
  {{- else }}
  replicas: 1
  {{- end }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-yarn-rm
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: {{ .Values.global.repo }}/{{ .Values.yarn_rm.image }}
        env:
        - name: GLIBC_REPO
          value: {{ .Values.global.glibc_repo }}
        - name: GLIBC_VERSION
          value: {{ .Values.global.glibc_version }}
        - name: JAVA8_DOWNLOAD
          value: {{ .Values.global.java8_download }}
        - name: JAVA_INSTALL_VERSION
          value: {{ .Values.global.java8_install_version }}
        - name: BASH_REPO
          value: {{ .Values.global.bash_repo }}
        - name: BASH_APK
          value: {{ .Values.global.bash_apk }}
        - name: BASH_READLINE_APK
          value: {{ .Values.global.bash_readline_apk }}
        - name: BASH_NCURSES_APK
          value: {{ .Values.global.bash_ncurses_apk }}
        - name: HADOOP_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
        name: {{ template "fullname" . }}-yarn-rm
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: {{ .Values.yarn_rm.mem }}
          requests:
            memory: {{ .Values.yarn_rm.mem }}
            cpu: {{ .Values.yarn_rm.cpu }}
        volumeMounts:
        - mountPath: /opt/barbarian/hadoop/etc/hadoop
          name: yarn-cfg-volume
        ports:
        - containerPort: 8050
          name: server
        - containerPort: 8088
          name: webui-address
        - containerPort: 8025
          name: tracker
        - containerPort: 8030
          name: scheduler
        - containerPort: 8141
          name: admin
        command:
        - sh
        - -c
        - "/opt/barbarian/control/init.sh && bash /opt/barbarian/control/start-yarn-rm"
      volumes:
      - name: yarn-cfg-volume
        configMap:
          name: {{ template "fullname" . }}-yarn-rm-hadoop-conf
