apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-yarn-rm-hadoop-conf
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  yarn-site.xml: |-
{{ tpl (.Files.Get "files/yarn-rm/yarn-site.xml") . | indent 4 }}
  core-site.xml: |-
{{ tpl (.Files.Get "files/yarn-rm/core-site.xml") . | indent 4 }}
  mapred-site.xml: |-
{{ tpl (.Files.Get "files/yarn-rm/mapred-site.xml") . | indent 4 }}
  hdfs-site.xml: |-
{{ tpl (.Files.Get "files/yarn-rm/hdfs-site.xml") . | indent 4 }}
  capacity-scheduler.xml: |-
{{ tpl (.Files.Get "files/yarn-rm/capacity-scheduler.xml") . | indent 4 }}
  log4j.properties: |-
{{ tpl (.Files.Get "files/yarn-rm/log4j.properties") . | indent 4 }}
  hadoop-env.sh: |-
{{ tpl (.Files.Get "files/yarn-rm/hadoop-env.sh") . | indent 4 }}
  yarn.exclude: |-
    dead.ignoreme.local
