apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-zookeeper
  labels:
    app: {{ template "fullname" . }}-zookeeper
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ .Values.zookeeper.service.name }}-headless
  replicas: {{ .Values.zookeeper.count }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-zookeeper
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-zookeeper
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - {{ template "fullname" . }}-zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: {{ .Values.global.repo }}/{{ .Values.zookeeper.image }}
        name: {{ template "fullname" . }}-zookeeper
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /opt/barbarian/zookeeper/conf
          name: zk-cfg-volume
        - name: datadir
          mountPath: /opt/barbarian/zookeeper/data
        resources:
          requests:
            memory: "{{ .Values.zookeeper.mem }}"
            cpu: "{{ .Values.zookeeper.cpu }}"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "/opt/barbarian/control/start-zookeeper \
          --servers={{ .Values.zookeeper.count }} \
          --data_dir=/opt/barbarian/zookeeper/data \
          --data_log_dir=/opt/barbarian/zookeeper/data/log \
          --conf_dir=/opt/barbarian/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap={{ .Values.zookeeper.ps_mem }} \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level={{ .Values.zookeeper.log_level }}"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "/opt/barbarian/control/zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "/opt/barbarian/control/zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: datadir
        emptyDir: {}
      - name: zk-cfg-volume
        emptyDir: {}
