apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.service.name }}
  labels:
    app: {{ template "fullname" . }}-zookeeper
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: {{ template "fullname" . }}-zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.service.name }}-headless
  labels:
    app: {{ template "fullname" . }}-zookeeper
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}-zookeeper
