apiVersion: v1
description: Barbarian is a big data system founded on Apache Hadoop offering Hive, LLAP and Tez for fast SQL datawarehousing at scale.
name: barbarian
version: 0.1.2-badh1
icon: https://barbarians.io/barbarians.png
appVersion: 0.1.0
maintainers:
- name: grobbie
  email: rob@barbarians.io
