# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: dockerbarbarians
  hadoop_conf_dir: /opt/barbarian/hadoop/etc/hadoop
  log_level: INFO
  log_dir: /tmp

  # set to true if you want to automatically install the Tez sharelib to 
  # the cluster's distributed filesystem
  tez_init: true

hive_hms:
  image: hive:latest

  # set to true to enable N+N HA for the Hive Metastore
  ha_enabled: true

  cpu: 1
  mem: 2Gi

  # set db_auto: true if you want Helm to automatically install a mariadb
  # for hive metastore persistent backend
  db_auto: true

  # specify if the database schema should be initialized on deployment.
  # will fail with an error if the schema is already present
  db_init: true

  # specify the jdbc uri for your hive metastore persistent backend.
  # Barbarian supports postgres, mssql, mariadb or mysql
  db_uri: YOUR_DB_URI

  # specify the type of database for your hive metastore persistent backend.
  # Barbarian supports the following values here: postgres, mssql or mysql.
  # If you want to use MariaDB, then you should specify "mysql".
  # NB. currently tested with MariaDB.
  db_type: mysql

  # specify the driver class to use. Currently tested with MariaDb, other
  # drivers will follow
  db_driver: "org.mariadb.jdbc.Driver"

  # specify the username for your hive metastore persistent backend.
  db_username: barbarian

  # specify the password for your hive metastore persistent backend.
  # if db_auto is true then you should set the password for mariadb.db.password instead
  # (see below in mariadb section).
  db_password: "YOUR_DB_PASSWORD"

  service:
    name: hmsserv

hive_hs2:
  image: hive:latest
  count: 1
  llapd_enabled: true
  llapd_count: 4
  mem: 2Gi
  cpu: 1
  llapd_mem: 2g
  log_level: INFO

  # if you want to expose HiveServer2 to the outside world
  ingress_enabled: false

  service:
    name: hs2serv

yarn_rm:
  image: barbarian-base:latest

  # set to true to enable YARN RM HA
  ha_enabled: true
  cpu: 1
  mem: 2Gi

  service:
    name: yarnrmserv

yarn_nm:
  image: barbarian-base:latest
  count: 5
  cpu: 2
  mem: 4Gi
  container_mem: 4g
  container_vcpu: 2

  service:
    name: yarnnmserv

zookeeper:
  image: zookeeper:latest
  count: 5
  cpu: 0.5
  mem: 2Gi

  service:
    name: zkserv

ignite:
  image: ignite:latest
  count: 5
  cpu: 2
  mem: 4Gi

  # set to true to enable an ingress flow to expose IGFS to the outside
  ingress_enabled: false

  # set to true to enable secondary storage system
  # otherwise ignite in-memory filesystem will be the primary
  # storage backend (useful for evaluation/testing only)
  secondary_fs_enabled: false

  # hybrid mode allows igfs to act as the primary storage system with the secondary filesystem
  # mounted at the path '/external'
  hybrid: false

  # how many data replicas igfs should maintain for durability
  data:
    replicas: 3

  # how many metadata replicas igfs should maintain for durability
  meta:
    replicas: 3  

  # currently only supports s3a. support for adls, google cloud storage and ceph
  # will follow
  secondary_fs_uri: s3a://YOUR_BUCKET/
  hadoop_conf_dir: /opt/hadoop/etc/hadoop

  s3a:
    access_key_id: YOUR_ACCESS_KEY_ID
    secret_access_key: YOUR_SECRET_ACCESS_KEY
    endpoint: s3-eu-west-1.amazonaws.com
    ssl_enabled: true
    s3guard_ddb:
      create: true
      region: eu-west-1
      capacity:
        read: 3
        write: 3

  service:
    name: igniteserv

# A bitnami mariadb can optionally be deployed by Helm for testing purposes.
# For production deployments a dedicated external database is recommended.
# Barbarians supports connection to postgres, mssql, mariadb and mysql.
mariadb:
  replication:
    enabled: false
  db:
    name: hive_metastore
    user: barbarian
    password: password123!

    # rootUser:
      # password:

  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
